---

- name: "Playbook: Test"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - name: test python
      shell: |
        print("Hello World")
      args:
        executable: /alex/python/venv/bin/python3
      vars:
        ansible_connection: "{{ prop_ansible_connection }}"
        ansible_host: "{{ prop_host.ipaddress }}"
      become: true

